### ISSUE TITLE
What is crunching?

### ISSUE THREAD

**Issue by deavmi** [2mac/sndcrunch#1]
What is audio crunching? I'd like to know?

**Comment by 2mac** [comment]
True bit crunching is reducing the [bit depth](https://en.wikipedia.org/wiki/Audio_bit_depth) of a wave.

However, it turns out that 16-bit and even 8-bit waves can be incredibly detailed. During my tests, I was unable to notice a significant difference between the original input and my 8-bit output wave.

Because of that, I have done some fake crunching which gives the distorted sound I was looking for. Try recording your own voice and then passing the audio through this program to see the aesthetic it produces.

I'm about to make some minor changes to improve the quality.

**Comment by deavmi** [comment]
So it lowers the quality and make chiptune like music? :smile_cat:

**Comment by 2mac** [comment]
Well, kind of, but not really. Chiptune certainly works with lower bit depth, but if you stick a song through this, it won't come out as good chiptune. I've tried music with this, and it's okay, but not great.

I designed it for human voices so that you would get a sound like the ones of people speaking in old arcade games like the announcer on Pole Position.

**Comment by deavmi** [comment]
Oh, awesome, so it would have some elements of chiptune like that graininess like you mentioned (distortion).

**Comment by 2mac** [comment]
Yes. This program was just an experiment playing with sound files. I'll soon me making another more interesting program using this library.

**Comment by deavmi** [comment]
Cool. Maybe a web-app that can make video-game voices (arcade style) using this library. Or using the executable which in turn uses the library.

**Comment by 2mac** [comment]
That could be cool. I'll look into that.

**Comment by deavmi** [comment]
Yeah. :). And maybe you cab choose some settings. Like if you want to change the general pitch of the audio as well.

**Comment by deavmi** [comment]
And have preset configurations for specific well-known arcade characters.

**Comment by deavmi** [comment]
> "That could be cool. I'll look into that."

Awesome. :)

**Comment by 2mac** [comment]
Problem with running it as a web app is server load. Audio transcoding (this is technically a transcoder) is a heavy process. It would be easy to exploit a server like that. This might best be kept on the client.

Changing the pitch is more of an audio editing task. I'd recommend someone use a program like Audacity for that.

**Comment by deavmi** [comment]
Well you can limit an IP to a certain anount of transcodes.

**Comment by 2mac** [comment]
Tor can get around that easily. The other problem is that even legitimate users are going to weigh down a server. If I have even three people trying to run this at once, it will likely lock up my web server to unbearable speeds.

**Comment by deavmi** [comment]
@2mac True and VPNs. I was thinking about that.
